# Specifies the version of the Docker Compose file format
version: '3.8'

# Defines the services (containers) that make up your application
services:
  # This is the service for your Go backend
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: your_postgres_password # <-- CHANGE THIS
      DB_NAME: postgres
    depends_on:
      - db

  # This is the service for your PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_postgres_password # <-- USE THE SAME PASSWORD
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Defines a named volume to persist database data
volumes:
  postgres_data: